[package]
name = "rust_ast_parser"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "rust_ast_parser"
path = "rust_ast_parser.rs"

[dependencies]
syn = { version = "1.0", features = ["full", "extra-traits"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
quote = "1.0"